# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90)),
                ('address', models.CharField(default='', max_length=255)),
                ('is_activate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Cash_', help_text='Asigne un nuevo nombre a la caja registradora', max_length=9)),
                ('is_active', models.BooleanField(default=False)),
                ('branch_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchoffices.BranchOffice')),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('image', models.ImageField(upload_to='media/suppliers')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('id',),
            },
        ),
    ]
