# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('AS', 'Ensamblado')], default='AS', max_length=10)),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos Procesados',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PR', 'Provider'), ('ST', 'Stock'), ('AS', 'Assembled'), ('SO', 'Sold')], default='PR', max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('quantity', models.FloatField(default=0)),
                ('waste', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('supply', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Supply')),
            ],
            options={
                'verbose_name': 'Insumo en Almacén',
                'verbose_name_plural': 'Insumos en el Almacén',
                'ordering': ('id',),
            },
        ),
    ]
