# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branchoffices', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PR', 'En proceso'), ('SO', 'Vendido'), ('CA', 'Cancelado')], default='PR', max_length=10)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('pin', models.CharField(default='1234', max_length=254)),
            ],
            options={
                'verbose_name': 'Pedido del Cliente',
                'verbose_name_plural': 'Pedidos de los Clientes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalles del Pedido del Cliente',
                'verbose_name_plural': 'Detalles de los Pedidos de Clientes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IP', 'Pedido'), ('RE', 'Recibido'), ('CA', 'Cancelado')], default='IP', max_length=2)),
            ],
            options={
                'verbose_name': 'Pedido al Proveedor',
                'verbose_name_plural': 'Pedidos a Proveedores',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.SupplierOrder')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchoffices.Supplier')),
                ('supply', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Supply')),
            ],
            options={
                'verbose_name': 'Detalles del Pedido a Proveedor',
                'verbose_name_plural': 'Detalles de Pedidos a Proveedores',
                'ordering': ('id',),
            },
        ),
    ]
