# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_ticket_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_type',
            field=models.CharField(choices=[('CA', 'Efectivo'), ('CR', 'Crédito')], default='CA', max_length=2),
        ),
    ]
