# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_ticket_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
