# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branchoffices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(choices=[('FD', 'Platillos'), ('CO', 'Complementos')], default='FD', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cartridges')),
            ],
            options={
                'verbose_name': 'Cartucho',
                'verbose_name_plural': 'Cartuchos',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CartridgeRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cartridge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Cartridge')),
            ],
            options={
                'verbose_name': 'Receta del Cartucho',
                'verbose_name_plural': 'Recetas de Cartuchos',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PackageCartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('package_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dabba',
                'verbose_name_plural': 'Dabbas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PackageCartridgeRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cartridge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Cartridge')),
                ('package_cartridge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.PackageCartridge')),
            ],
            options={
                'verbose_name': 'Receta del Dabba',
                'verbose_name_plural': 'Recetas de Dabbas',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SuppliesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('image', models.ImageField(upload_to='supplies-categories')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('barcode', models.PositiveIntegerField(blank=True, help_text='(Código de barras de 13 dígitos)', null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('storage_required', models.CharField(choices=[('DR', 'Ambiente Seco'), ('RE', 'Refrigeración'), ('FR', 'Congelación')], default='DR', max_length=2)),
                ('presentation_unit', models.CharField(choices=[('PA', 'Paquete'), ('BO', 'Caja'), ('PI', 'Pieza')], default='PA', max_length=10)),
                ('presentation_cost', models.FloatField(default=0)),
                ('measurement_quantity', models.FloatField(default=0)),
                ('measurement_unit', models.CharField(choices=[('GR', 'gramo'), ('MI', 'mililitro'), ('PI', 'pieza')], default='PA', max_length=10)),
                ('optimal_duration', models.IntegerField(default=0)),
                ('optimal_duration_unit', models.CharField(choices=[('DA', 'Dias'), ('MO', 'Meses'), ('YE', 'Años')], default='DA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='supplies')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.SuppliesCategory')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SupplyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=90)),
                ('branch_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchoffices.BranchOffice')),
            ],
            options={
                'verbose_name': 'Ubicación del Insumo',
                'verbose_name_plural': 'Ubicación de los Insumos',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.SupplyLocation'),
        ),
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchoffices.Supplier'),
        ),
        migrations.AddField(
            model_name='cartridgerecipe',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Supply'),
        ),
    ]
